
MOV SI,1301H      ; SET SI AS THE POINTER FOR FIRST INPUT MATRIX
MOV DI,1401H      ; SET DI AS THE POINTER FOR SECOND INPUT MATRIX
MOV BP,1501H      ; SET BP AS THE POINTER FOR PRODUCT MATRIX
MOV CL,03H        ; SET CL S COUNT FOR ELEMENTS IN A ROW
MOV CH,03H        ; SET CH S COUNT FOR ELEMENTS IN A COLUMN
MOV DH,CH
REPEAT3:
MOV BL,DH         ; COPY THE COLUMN COUNT IN BL REGISTER
REPEAT2:
MOV DL,00H        ; INTIALIZE SUM AS ZERO
MOV CH,DH         ; GET THE COULUMN COUNT IN DH
REPEAT1:
MOV AL,[SI]       ; GET ONE ELEMENT OF THE ROW IN AL REGISTER 
MUL [DI]          ; GET THE PRODUCT OF ROW AND COLUMN ELEMENT IN AL
ADD DL,AL         ; ADD THE PRODUCT TO SUM
INC SI            ; INCREMENT THE FIRST INPUT MATRIX POINTER
ADD DI,03         ; LET DI POINTER TO NEXT ELEMENT OF SAME COLUMN OF 2ND MATRIX 
DEC CH            ; DECREMENT OF COLUMN COUNT
JNZ REPEAT1       ; REPEAT MULTIPLICATION AND ADDITION UNTIL DH COUNT IS ZERO
MOV [BP],DL       ; STORE AN ELEMENT OF PRODUCT MATRIX IN MEMORY
INC BP            ; INCREMENT THE PRODUCT MATRIX POINTER
SUB SI,03H        ; MAKE SI TO POINT THE FIRST ELEMENT OF THE ROW
SUB DI,09H
INC DI
DEC BL            ; DECREMENT COLUMN COUNT 
JNZ REPEAT2
ADD SI,03H        ; LET SI POINTER FIRST ELEMENT OF SECOND MATRIX
MOV DI,1401H      ; MAKE DI TO POINT TO FIRST ELEMENT OF 2 ND MATRIX
DEC CL            ; DECREMENT OF ROW COUNT
JNZ REPEAT3      
HLT               ; HALT AND EXECUTION